replicaCount: 1  # Number of replicas

image:
  repository: digiotech/digio-ckyc
  tag: digio_ckyc_v0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ckycConfig:
  fiCode: "YOUR_FI_CODE"
  digioEnv: "PROD"
  publicKeyPath: "/app/ckyc-keys/CersaiSignPublicKey.cer"

keystore:
  encodedKeystore: "BASE64_ENCODED_STRING_HERE"  # Replace with actual base64-encoded keystore.jks base64 mykeystore.jks | tr -d '\n'
  keyAlias: "my-alias"
  password: "979436"
  keystorePath: "/app/keystore/mykeystore.jks"
  signatureMethod: "http://www.w3.org/2000/09/xmldsig#rsa-sha1"

volumeMounts:
  - name: ckyc-keys
    mountPath: /app/ckyc-keys
  - name: ckyc-keystore
    mountPath: /app/keystore
    subPath: mykeystore.jks

volumes:
  - name: ckyc-keys
    configMap:
      name: "{{ .Release.Name }}-config"
  - name: ckyc-keystore
    secret:
      secretName: "{{ .Release.Name }}-keystore"

serviceAccount:
  create: false
  name: ""

database:
  port: 5432

autoscaling:
  enabled: false  
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false  # Change to true if using Ingress
  annotations: {}
  hosts:
    - host: ckyc.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
