replicaCount: 1  # Number of replicas

image:
  repository: digiotech/digio-ckyc
  tag: digio_ckyc_v0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ckycConfig:
  fiCode: YOUR_FI_CODE
  digioEnv: PROD
  publicKeyPath: /app/ckyc-keys/CersaiSignPublicKey.cer

keystore:
  keyAlias: mykeys
  keystorePassword: 979436
  keystorePath: /app/ckyc-keys/mykeystore.jks
  signatureMethod: http://www.w3.org/2000/09/xmldsig#rsa-sha1

volumeMounts:
  - name: ckyc-keys
    mountPath: /app/ckyc-keys

volumes:
  - name: ckyc-keys
    configMap:
      name: ckyc-config

serviceAccount:
  create: false
  name: ""

database:
  port: 5432

autoscaling:
  enabled: false  
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false  # Change to true if using Ingress
  annotations: {}
  hosts:
    - host: ckyc.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

