apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  FI_CODE: "{{ .Values.ckycConfig.fiCode }}"
  DIGIO_ENV: "{{ .Values.ckycConfig.digioEnv }}"
  PUBLIC_KEY_PATH: "{{ .Values.ckycConfig.publicKeyPath }}"
  KEYSTORE_PATH: "{{ .Values.keystore.keystorePath }}"
  SIGNATURE_METHOD: "{{ .Values.keystore.signatureMethod }}"

