apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  FI_CODE: "{{ .Values.ckycConfig.fiCode }}"
  DIGIO_ENV: "{{ .Values.ckycConfig.digioEnv }}"
  PUBLIC_KEY_PATH: "/app/ckyc-keys/CersaiSignPublicKey.cer"
  KEYSTORE_PATH: "/app/keystore/mykeystore.jks"
  SIGNATURE_METHOD: "{{ .Values.keystore.signatureMethod }}"
  CersaiSignPublicKey.cer: |
    {{ .Files.Get "digio-ckyc/ckyc-keys/CersaiSignPublicKey.cer" | indent 4 }}
