apiVersion: v1
kind: Secret
metadata:
  name: ckyc-secret
type: Opaque
data:
  keystore.jks: {{ .Values.keystore.encodedKeystore | quote }}
  keystore-password: {{ .Values.keystore.password | b64enc | quote }}
