apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keystore
type: Opaque
data:
  keystore-password: {{ .Values.keystore.password | b64enc }}
  mykeystore.jks: {{ .Values.keystore.encodedKeystore | quote }}
